import { registerDemo } from '../../core/registry';
import { RaymarcherDemo } from './raymarcher';
import { FractalDemo } from './fractal';
import { DomainWarpDemo } from './domainwarp';
import { ReactionDiffusionDemo } from './reaction';
import { JellyfishDemo } from './jellyfish';
import { HyperbolicDemo } from './hyperbolic';
import { BlackHoleDemo } from './blackhole';
import { TesseractDemo } from './tesseract';
import { LeniaDemo } from './lenia';
import { MyceliumDemo } from './mycelium';
import { QuantumFoamDemo } from './quantum';
import { KleinFlowDemo } from './klein';

registerDemo(new RaymarcherDemo());
registerDemo(new FractalDemo());
registerDemo(new DomainWarpDemo());
registerDemo(new ReactionDiffusionDemo());
registerDemo(new JellyfishDemo());
registerDemo(new HyperbolicDemo());
registerDemo(new BlackHoleDemo());
registerDemo(new TesseractDemo());
registerDemo(new LeniaDemo());
registerDemo(new MyceliumDemo());
registerDemo(new QuantumFoamDemo());
registerDemo(new KleinFlowDemo());
